CREATE DATABASE sales_analysis;
USE sales_analysis;

CREATE TABLE sales_data (
    OrderID INT,
    Order_Date DATE,
    Region VARCHAR(50),
    Product VARCHAR(50),
    Category VARCHAR(50),
    Quantity INT,
    Sales DECIMAL(15,2)
);

SELECT COUNT(*) FROM sales_data;
SELECT * FROM sales_data;

/* =======================================================
   Sales Data Analysis Project
   Author: Krunal Patil

   Simple SQL analysis on a sales dataset (50k records)
   to understand revenue, product performance, and region
   wise sales distribution.
======================================================= */



-- Query 1
-- Get the total sales revenue from the dataset
SELECT SUM(Sales) AS total_sales
FROM sales_data;



-- Query 2
-- Count how many orders exist in the table
SELECT COUNT(Order_ID) AS total_orders
FROM sales_data;



-- Query 3
-- Calculate total quantity of products sold
SELECT SUM(Quantity) AS total_quantity_sold
FROM sales_data;



-- Query 4
-- Check how much sales each region generated
SELECT Region,
SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Region
ORDER BY total_sales DESC;



-- Query 5
-- Compare sales between product categories
SELECT Category,
SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Category
ORDER BY total_sales DESC;



-- Query 6
-- Find the top 10 products based on revenue
SELECT Product,
SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Product
ORDER BY total_sales DESC
LIMIT 10;



-- Query 7
-- Calculate the average order value
SELECT AVG(Sales) AS avg_order_value
FROM sales_data;



-- Query 8
-- Count number of orders coming from each region
SELECT Region,
COUNT(Order_ID) AS total_orders
FROM sales_data
GROUP BY Region
ORDER BY total_orders DESC;



-- Query 9
-- Get the order with the highest sales value
SELECT *
FROM sales_data
ORDER BY Sales DESC
LIMIT 1;



-- Query 10
-- Get the order with the smallest sales value
SELECT *
FROM sales_data
ORDER BY Sales ASC
LIMIT 1;



-- Query 11
-- Total sales generated by each product
SELECT Product,
SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Product
ORDER BY total_sales DESC;



-- Query 12
-- Average sales value for each region
SELECT Region,
AVG(Sales) AS avg_sales
FROM sales_data
GROUP BY Region
ORDER BY avg_sales DESC;



-- Query 13
-- Number of orders in each product category
SELECT Category,
COUNT(Order_ID) AS total_orders
FROM sales_data
GROUP BY Category
ORDER BY total_orders DESC;



-- Query 14
-- Highest single sale recorded in each region
SELECT Region,
MAX(Sales) AS highest_sale
FROM sales_data
GROUP BY Region;



-- Query 15
-- Lowest sale value recorded in each region
SELECT Region,
MIN(Sales) AS lowest_sale
FROM sales_data
GROUP BY Region;



-- Query 16
-- Daily sales revenue
SELECT Order_Date,
SUM(Sales) AS daily_sales
FROM sales_data
GROUP BY Order_Date
ORDER BY Order_Date;



-- Query 17
-- Monthly sales trend
SELECT MONTH(Order_Date) AS month,
SUM(Sales) AS monthly_sales
FROM sales_data
GROUP BY month
ORDER BY month;



-- Query 18
-- Top regions by total revenue
SELECT Region,
SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Region
ORDER BY total_sales DESC
LIMIT 5;



-- Query 19
-- Products that sold more than 1000 units
SELECT Product,
SUM(Quantity) AS total_quantity
FROM sales_data
GROUP BY Product
HAVING SUM(Quantity) > 1000
ORDER BY total_quantity DESC;



-- Query 20
-- Sales breakdown by region and category
SELECT Region,
Category,
SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Region, Category
ORDER BY Region, total_sales DESC;

-- Query 21
-- Rank products based on total sales revenue
-- Higher sales means better rank

SELECT 
    Product,
    SUM(Sales) AS total_sales,
    RANK() OVER (ORDER BY SUM(Sales) DESC) AS sales_rank
FROM sales_data
GROUP BY Product;



-- Query 22
-- Running total of sales by date
-- This helps track cumulative revenue growth over time

SELECT 
    Order_Date,
    SUM(Sales) AS daily_sales,
    SUM(SUM(Sales)) OVER (ORDER BY Order_Date) AS running_total_sales
FROM sales_data
GROUP BY Order_Date
ORDER BY Order_Date;



-- Query 23
-- Compare each product's sales with the average product sales
-- Useful to identify products performing above average

SELECT 
    Product,
    SUM(Sales) AS total_sales,
    AVG(SUM(Sales)) OVER () AS avg_product_sales
FROM sales_data
GROUP BY Product;



-- Query 24
-- Rank regions based on total sales
-- Shows which region performs best

SELECT 
    Region,
    SUM(Sales) AS total_sales,
    DENSE_RANK() OVER (ORDER BY SUM(Sales) DESC) AS region_rank
FROM sales_data
GROUP BY Region;



-- Query 25
-- Calculate percentage contribution of each category to total sales
-- Useful for understanding category market share

SELECT 
    Category,
    SUM(Sales) AS category_sales,
    ROUND(
        SUM(Sales) * 100.0 / SUM(SUM(Sales)) OVER (), 
        2
    ) AS sales_percentage
FROM sales_data
GROUP BY Category
ORDER BY category_sales DESC;